<?php

/**
 * This is the model base class for the table "client_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClientType".
 *
 * Columns in table "client_type" available as properties of the model,
 * followed by relations of table "client_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $concrete_details
 *
 * @property Client[] $clients
 */
abstract class BaseClientType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'client_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClientType|ClientTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description', 'required'),
			array('name, description', 'length', 'max'=>45),
			array('concrete_details', 'length', 'max'=>200),
			array('concrete_details', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, concrete_details', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clients' => array(self::HAS_MANY, 'Client', 'client_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'concrete_details' => Yii::t('app', 'Concrete Details'),
			'clients' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('concrete_details', $this->concrete_details, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}