<?php

/**
 * This is the model base class for the table "alarm_config".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AlarmConfig".
 *
 * Columns in table "alarm_config" available as properties of the model,
 * followed by relations of table "alarm_config" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $client_id
 * @property string $categories
 *
 * @property Client $client
 * @property AlarmLog[] $alarmLogs
 */
abstract class BaseAlarmConfig extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'alarm_config';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AlarmConfig|AlarmConfigs', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('client_id', 'required'),
			array('client_id', 'numerical', 'integerOnly'=>true),
			array('name, categories', 'length', 'max'=>45),
			array('name, categories', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, client_id, categories', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'client' => array(self::BELONGS_TO, 'Client', 'client_id'),
			'alarmLogs' => array(self::HAS_MANY, 'AlarmLog', 'alarm_config_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'client_id' => null,
			'categories' => Yii::t('app', 'Categories'),
			'client' => null,
			'alarmLogs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('client_id', $this->client_id);
		$criteria->compare('categories', $this->categories, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}